; DRAMSim Device Configuration File

[device]
; --- Architectural Parameters ---
NUM_BANKS=8
NUM_ROWS=16384     
NUM_COLS=1024  
DEVICE_WIDTH=8  

; --- Timing Parameters ---
t_REFI=7800
t_RFC=110            ; Refresh Cycle Time
t_RCD=14             ; RAS-to-CAS delay
t_RP=14              ;  PRECHARGE
t_CL=14              ; CAS Latency
t_RAS=35             ; Row Active Time
t_WR=15              ; Write Recovery