; DRAMSim System Configuration File

[system]
; --- Queue Configuration ---
TRANS_QUEUE_DEPTH=32      ; Command Queue Size

; --- Controller Policies ---
SCHEDULING_POLICY=FR_FCFS ; FCFS / FR_FCFS
ROW_BUFFER_POLICY=open_page ;

; --- Bus data ---
SYSTEM_DATA_WIDTH=64
ADDRESS_MAPPING_POLICY=Scheme1 ; Row-Bank-Col-Channel